variable = 10;
print(type(variable));
variable = 10.1;
print(type(variable));
variable = True;
print(type(variable));
variable = "101";
print(type(variable));
variable = [10,10,10];
print(type(variable));
